# Generated by Django 5.2 on 2025-06-28 22:10

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0067_noticia_contador_visitas_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
