# Generated by Django 5.2 on 2025-06-29 22:48

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0069_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='mostrar_creditos',
            field=models.BooleanField(default=True, help_text='Si está marcado, se mostrarán los datos del autor y editores de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
