# Generated by Django 5.2 on 2025-07-05 13:56

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0070_noticia_mostrar_creditos_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
