# Generated by Django 5.2 on 2025-07-05 23:33

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0071_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='diarioback__estado__fd9625_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-contador_visitas'], name='diarioback__estado__968360_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-contador_visitas_total'], name='diarioback__estado__560959_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', 'categorias'], name='diarioback__estado__308a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_publicacion'], name='diarioback__fecha_p_afef10_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['slug'], name='diarioback__slug_30cbf1_idx'),
        ),
    ]
