# Generated by Django 5.2 on 2025-07-07 13:53

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0072_alter_noticia_options_alter_noticia_categorias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-contador_visitas']},
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__estado__fd9625_idx',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__estado__968360_idx',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__estado__560959_idx',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__estado__308a2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__fecha_p_afef10_idx',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='diarioback__slug_30cbf1_idx',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
