# Generated by Django 5.2 on 2025-11-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0074_alter_noticia_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('imagen_local', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='noticiavisita',
            name='noticia',
        ),
        migrations.AlterUniqueTogether(
            name='reaccionnoticia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reaccionnoticia',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='reaccionnoticia',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='contador_visitas',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='contador_visitas_total',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tiene_comentarios',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='ultima_actualizacion_contador',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='NoticiaVisita',
        ),
        migrations.DeleteModel(
            name='ReaccionNoticia',
        ),
    ]
