# Generated by Django 5.2 on 2025-11-09 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0075_servicio_remove_noticiavisita_noticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('consultoria_estrategica', 'Consultoría Estratégica'), ('capacitaciones_especializadas', 'Capacitaciones Especializadas')], default='consultoria_estrategica', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Subcategoría de Servicio',
                'verbose_name_plural': 'Subcategorías de Servicios',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='diarioback.subcategoriaservicio', verbose_name='Subcategoría'),
        ),
    ]
