# Generated by Django 5.2 on 2025-11-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0076_subcategoriaservicio_servicio_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('token_confirmacion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
