# Generated by Django 5.2.8 on 2025-11-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0077_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
