# Generated by Django 5.2.8 on 2025-11-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0079_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['activo', 'subcategoria'], name='servicio_activo_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['-fecha_creacion'], name='servicio_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['slug'], name='servicio_slug_idx'),
        ),
    ]
