# Generated by Django 5.2.8 on 2025-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0080_alter_servicio_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['leido', '-fecha_envio'], name='contacto_leido_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['respondido', '-fecha_envio'], name='contacto_resp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['leido', 'respondido', '-fecha_envio'], name='contacto_estado_idx'),
        ),
    ]
