# Generated by Django 5.2.8 on 2025-11-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0081_alter_contacto_fecha_envio_alter_contacto_leido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nombre_noticia',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='noticia_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['autor', '-fecha_publicacion'], name='noticia_autor_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['nombre_noticia'], name='noticia_titulo_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion', 'mostrar_creditos'], name='noticia_pub_idx'),
        ),
    ]
