# Generated by Django 5.2.8 on 2025-12-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0082_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoriaservicio',
            options={'verbose_name': 'Categoría de Servicio', 'verbose_name_plural': 'Categorías de Servicios'},
        ),
        migrations.AddField(
            model_name='subcategoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del servicio', null=True),
        ),
        migrations.AddField(
            model_name='subcategoriaservicio',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre del ícono (ej: fa-chart-line)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoriaservicio',
            name='nombre',
            field=models.CharField(choices=[('estrategias_impacto', 'Estrategias y reportes de impacto'), ('asuntos_corporativos', 'Asuntos corporativos y vinculación institucional'), ('comunicacion_estrategica', 'Comunicación estratégica y reputación'), ('analisis_datos', 'Análisis y datos'), ('informes_tecnicos', 'Informes técnicos y posicionamiento temático')], default='estrategias_impacto', max_length=50, unique=True),
        ),
    ]
